import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <h3>This is header </h3>
        </div>
        <div>{children}</div>
        <div>
          <h2>this is footer</h2>
        </div>

      </body>
    </html>
  );
}
